### ISSUE TITLE
please add changelog to f-droid, thanks

### ISSUE THREAD

**Issue by treakiandroid** [janosgyerik/bluetoothviewer#14]
No further text

**Comment by TameOfGroans** [comment]
Given the wording in the wiki it seems unlikely the developer is the maintainer. 

https://f-droid.org/wiki/page/net.bluetoothviewer 

Thus the place for that request seems to be best suited to the fdroid forums. 

https://f-droid.org/forums/forum/apps/

**Comment by janosgyerik** [comment]
The content on f-droid seems to be generated, I didn't write it. I'm not really familiar with f-droid. If you think there are great benefits in maintaining that, and if you think I should maintain that, I'll be interested in your reasoning, so please shed some light. For now, I'm closing this issue.
