### ISSUE TITLE
Connect automatically to device 

### ISSUE THREAD

**Issue by GeRyCh91** [janosgyerik/bluetoothviewer#16]
Hi!
I saw in your code you can detect when lost connection do device. 
But what if I want to connect automatically to one of my paired devices when its bluetooth turned on again for example?
I mean is there any way to monitor reachability of one of my paired devices?
Any help will be appreciated!
Regards

**Comment by janosgyerik** [comment]
Connecting to a Bluetooth device needs the MAC address parameter. If I remember correctly, if you try to connect to a MAC address that is not available (not within range or no such device), then you will know the failure only when you try to read from the socket. 

You can write a program that periodically tries to connect to a device (a specific MAC address) until it succeeds. It seems doable. Would you like such feature in this app? Would you be willing to pay for it?  :moneybag: :wink:

**Comment by GeRyCh91** [comment]
@janosgyerik , first of all thank you for your reply!
Actually I work with very specific kind of bluetooth device. To sum up it's a card reader. With its help I can communicate with smart cards. So I suppose it's something in the middle. Means it may be regarded as a headset from one side, but regular device from another. It can send/receive messages to/from card. Probably solution going to be more complex. I hope I wrong :(
Anyway thank you for your suggestion!

p.s. I wish I could allow myself to pay you, bro! Frankly, I'm fed up trying to find solution to my problem..

**Comment by janosgyerik** [comment]
I hope the outline I explained above will help you. This seems doable.
